GameStore/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameStore;
using GameStore.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Routing;
using GameStore.Models;

namespace GameStore.Controllers
{
    public class GamesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;
        public GamesController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Game.Include(g => g.Category).Include(g => g.Company).Include(g => g.Downloads);
            return View(await applicationDbContext.ToListAsync());
        }


        [HttpPost]
        public async Task<IActionResult> Index([FromForm] DateTime? from, [FromForm] DateTime? to, [FromForm] string name)
        {
            var games = await _context.Game.Include(g => g.Category).Include(g => g.Company).Include(g => g.Downloads)
                .Where(x => x.Name.Contains(name) &&
            (from == null || x.ReleaseDate >= from) &&
             (to == null || x.ReleaseDate <= to)
            ).ToListAsync();

            //   var applicationDbContext = _context.Game.Include(g => g.Category).Include(g => g.Company).Include(g => g.Downloads);
            return View(games);
        }
        public async Task<IActionResult> Table()
        {
            var applicationDbContext = _context.Game.Select(x => new DataTableDTO
            {
                Age = x.GameAge,
                Category = x.Category.CategoryName,
                Company = x.Company.CompanyName,
                DownloadCount = x.Downloads.Count,
                Image = x.Image,
                Name = x.Name,
                ReleaseDate = x.ReleaseDate.Value.ToString("yyyy/mm/dd")
            });
            return View(await applicationDbContext.ToListAsync());
        }
        [HttpPost]
        [Route("Download")]
        public async Task<IActionResult> Download([FromForm] int id, [FromForm] string email, [FromForm] string Comment)
        {
            var game = await _context.Game.FirstOrDefaultAsync(x => x.GameId == id);
            _context.Downloads.Add(new Models.Download
            {
                Comment = Comment,
                Date = DateTime.Now,
                Email = email,
                GameId = id
            });
            _context.SaveChanges();
            //   var applicationDbContext = _context.Game.Include(g => g.Category).Include(g => g.Company).Include(g => g.Downloads);
            return Redirect($"/files/{game.Filename}");
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .Include(g => g.Category)
                .Include(g => g.Company)
                .Include(g => g.Downloads)
                .Include(g => g.Updates)
                .FirstOrDefaultAsync(m => m.GameId == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName");
            ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "CompanyName");
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GameId,Name,Filename,ImageFile,GameFile,DateAdded,CompanyId,CategoryId,ReleaseDate,Description")] Game game)
        {
            if (ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                var ms = game.ImageFile.OpenReadStream();
                var bytes = new byte[ms.Length];
                ms.Position = 0;
                ms.Read(bytes, 0, (int)ms.Length);
                string filename = $"i{game.GameId}-{game.ImageFile.FileName.Replace(" ", "-")}";
                game.Image = filename;
                System.IO.File.WriteAllBytes(System.IO.Path.Combine(_env.WebRootPath, "files", filename), bytes);
                ms = game.GameFile.OpenReadStream();
                bytes = new byte[ms.Length];
                ms.Position = 0;
                ms.Read(bytes, 0, (int)ms.Length);
                filename = $"g{game.GameId}-{game.GameFile.FileName.Replace(" ", "-")}";
                game.Filename = filename;
                System.IO.File.WriteAllBytes(System.IO.Path.Combine(_env.WebRootPath, "files", filename), bytes);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName", game.CategoryId);
            ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "CompanyName", game.CompanyId);
            return View(game);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName", game.CategoryId);
            ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "CompanyName", game.CompanyId);
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GameId,Name,Filename,ImageFile,GameFile,DateAdded,CompanyId,CategoryId,ReleaseDate,Description")] Game game)
        {
            if (id != game.GameId)
            {
                return NotFound();
            }


            try
            {
                if (game.ImageFile != null)
                {
                    var ms = game.ImageFile.OpenReadStream();
                    var bytes = new byte[ms.Length];
                    ms.Position = 0;
                    ms.Read(bytes, 0, (int)ms.Length);
                    string filename = $"i{game.GameId}-{game.ImageFile.FileName.Replace(" ", "-")}";
                    game.Image = filename;
                    System.IO.File.WriteAllBytes(System.IO.Path.Combine(_env.WebRootPath, "files", filename), bytes);
                }
                if (game.GameFile != null)
                {
                    var ms = game.GameFile.OpenReadStream();
                    var bytes = new byte[ms.Length];
                    ms.Position = 0;
                    ms.Read(bytes, 0, (int)ms.Length);
                    var filename = $"g{game.GameId}-{game.GameFile.FileName.Replace(" ", "-")}";
                    game.Filename = filename;
                    System.IO.File.WriteAllBytes(System.IO.Path.Combine(_env.WebRootPath, "files", filename), bytes);

                }
                _context.Update(game);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GameExists(game.GameId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));


        }

        // GET: Games/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .Include(g => g.Category)
                .Include(g => g.Company)
                .FirstOrDefaultAsync(m => m.GameId == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var game = await _context.Game.FindAsync(id);
            _context.Game.Remove(game);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GameExists(int id)
        {
            return _context.Game.Any(e => e.GameId == id);
        }
    }
}

GameStore/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameStore.Data;
using GameStore.Models;
using Microsoft.AspNetCore.Authorization;

namespace GameStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RolesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationRole = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicationRole == null)
            {
                return NotFound();
            }

            return View(applicationRole);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] ApplicationRole applicationRole)
        {
            if (ModelState.IsValid)
            {
                _context.Add(applicationRole);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(applicationRole);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationRole = await _context.Roles.FindAsync(id);
            if (applicationRole == null)
            {
                return NotFound();
            }
            return View(applicationRole);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name")] ApplicationRole applicationRole)
        {
            if (id != applicationRole.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applicationRole);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationRoleExists(applicationRole.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(applicationRole);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationRole = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicationRole == null)
            {
                return NotFound();
            }

            return View(applicationRole);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationRole = await _context.Roles.FindAsync(id);
            if (_context.UserRoles.Any(x => x.RoleId == id))
            {
                ViewBag.Error = "There is a user with this role. The role cannot be removed.";
                return View(applicationRole);
            }
            else
            {
                
                _context.Roles.Remove(applicationRole);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
        }

        private bool ApplicationRoleExists(string id)
        {
            return _context.Roles.Any(e => e.Id == id);
        }
    }
}

GameStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@{ var controller = ViewContext.RouteData.Values["controller"]?.ToString()?.ToLower();}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/data-table.css" rel="stylesheet" />
    <link href="~/css/lightslider.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script>var _a = [];</script>
</head>
<body>
    <div class="d-flex" id="wrapper">
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading" style="height:88px;padding-left:.25em;padding-right:.25em;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <h1>Game Store</h1>
                </a>
            </div>
            <div class="list-group list-group-flush">
                <a asp-controller="Categories" asp-action="Index" data-controller="categories" con class="list-group-item list-group-item-action bg-light">Categories</a>
                <a asp-controller="Games" asp-action="Index" data-controller="games" class="list-group-item list-group-item-action bg-light">Games</a>
                <a asp-controller="Companies" asp-action="Index" data-controller="companies" class="list-group-item list-group-item-action bg-light">Companies</a>
                <a asp-controller="Updates" asp-action="Index" data-controller="updates" class="list-group-item list-group-item-action bg-light">Updates/Patches/Skins</a>
               @if (User.IsInRole("Admin"))
               {
                <a asp-controller="Roles" asp-action="Index" data-controller="roles" class="list-group-item list-group-item-action bg-light">Roles</a>
                <a asp-controller="UserRoles" asp-action="Index" data-controller="userroles" class="list-group-item list-group-item-action bg-light">User Roles</a>
               }
            </div>
        </div>

        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="height:88px;">
                <button class="btn btn-primary menubtn
                        " id="menu-toggle">
                    Menu
                </button>
                <div class="container" style="justify-content:flex-end !important;">

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <partial name="_LoginPartial" />


                </div>
            </nav>

            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; @DateTime.Now.Year - Avinder GameStore
                </div>
            </footer>

        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-datatable.js"></script>
    <script src="~/js/bootstrap-datatable.js"></script>
    <script src="~/js/lightslider.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
        $('.list-group-item').each(function () { if ($(this).data("controller") === '@controller') $(this).addClass('active'); });
        for (var i = 0; i < _a.length; i++)_a[i]();
    </script>
</body>
</html>